### ISSUE TITLE
sklearn is deprecated

### ISSUE THREAD

**Issue by parsifal9** [KevinMoonLab/RF-PHATE#1]
Hi KevinMoonLab,

I get an install error

```
> pip install git+https://github.com/KevinMoonLab/RF-PHATE
The 'sklearn' PyPI package is deprecated, use 'scikit-learn'
```

I downloaded the repository and changed sklearn to scikit-learn.
It now installs OK but I get an error. Is this because of the install, or are there different versions of the titanic data set floating around?
```
from rfphate import dataset, rfphate
import pandas as pd
import seaborn as sns

# Read in the data
data   = pd.read_csv('https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv', sep = ',')
x, y   = dataset.normalize_data(data, label_col = 0)

rfphate_op = rfphate.RFPHATE(random_state = 0)
emb = rfphate_op.fit_transform(x, y)

ValueError: Input X contains NaN.
RFPHATE does not accept missing values encoded as NaN natively. For supervised learning, you might want to 
consider 
sklearn.ensemble.HistGradientBoostingClassifier and Regressor which accept missing values encoded as NaNs 
natively. 
Alternatively, it is possible to preprocess the data, for instance by using an imputer transformer in a pipeline 
or drop samples 
with missing values. See https://scikit-learn.org/stable/modules/impute.html You can find a list of all estimators 
that handle 
NaN values at the following page: https://scikit-learn.org/stable/modules/impute.html#estimators-that-handle-nan-values
```
Bye

**Comment by parsifal9** [comment]
I see now that "titanic.csv" has lots of character variables etc. You must be using a curated version of this. So the only issue is the
install warning.

**Comment by jakerhodes** [comment]
Hi parsifal9,

Thank you for reaching out and for your interest in RF-PHATE.  This repository has (obviously) not been maintained and is set to be replaced with a repository with significant updates. The new repository is currently under construction and is not yet publicly available. 

I appreciate your feedback concerning implementations with missing values. We will be taking this into consideration. 

As for your comments about the Titanic dataset, RandomForestClassifier and RandomForestRegressor currently do not natively operate with categorical variables.  These must be numerically encoded. There is no perfect way of doing this to not affect random forest behavior.  One-hot encoding splits a variable into multiple variables, which affects the way the RF splits the data. Integer encoding implicitly determines an order for categorical variables, which often isn't desirable. This latter method was used in that example.

I hope to have a publicly available version of the updated repo soon.  Thanks again for your interest.


Jake

**Comment by parsifal9** [comment]
Thanks Jake. I will close the issue
